- spec_40.txt
> Problem: unclear explanatory text

- spec_40.txt
> Problem: XRAP cannot handle queries, custom metadata and etag and data modified in GET

- spec_21.txt
- spec_22.txt
- spec_37.txt
- spec_41.txt
- update
> Wrote CLIENT-SERVER RFC 41

- spec_22.txt
> Problem: link does not work

- spec_40.txt
Solution: use 'tracker' and clarify the text somewhat.
> Problem: 'sequence_no' is an ugly name

- spec_42.txt
- update
Solution: write new RFC 42 that fixes this, and deprecate RFC 22
(We'll deprecate it once we're happy with the changes)
> Problem: RFC 22 does not match current practice

- spec_42.txt
> Problem: copyright year is wrong on RFC 42

- spec_42.txt
> Problem: review comments on RFC 42

- 13/README.md
- 14/README.md
- 18/README.md
- 19/README.md
- 20/README.md
- 21/README.md
- 23/README.md
- 26/README.md
- 35/README.md
- 36/README.md
- 37/README.md
- 40/README.md
- 7/README.md
- 9/README.md
Solution: Use Markdown's heading syntax
> Problem: Wikidot ++++ heading was still used

- 21/README.md
Reference: https://www.gitbook.com/book/zeromq/rfc/build/573c3df72664611000587eb8
Solution: fix inline code formatting
> Problem: gitbook failing to build RFC 21

- 37/README.md
- spec_37.txt
Solution: clarify this in the text
> Problem: server/client roles aren't clearly defined for NULL

- book.js
Solution: Use a COSS plugin to generate all URLs
> Problem: COSS-formatted URLs were broken

- book.js
> Problem: gitbook 3.0.0-pre.15 has been superseded

- 33/README.md
- SUMMARY.md
- spec_33.txt
> Problem: 33/ZHTTP erroneously referred to as 8/ZHTTP

- book.js
Solution: use coss@1.0.4 plugin that copies them
> Problem: spec resources are not copied to spec:n

- 18/README.md
- 7/README.md
- 9/README.md
Solution: remove extra brackets
> Problem: incorrect image syntax

- 22/README.md
Solution: Mention the replacement RFC, same as RFC 16 does
> Problem: RFC 22 is superseded by RFC 42

- README.md
Solution: Add an explanation to the Introduction
> Problem: RFC states are not explained

- README.md
Solution: add it to initial list
> Problem: explanation of publication's states is duplicate

- README.md
Solution: point to COSS specification
> Problem: lifecycle differs from COSS

- SUMMARY.md
Solution: List it as Stable only
> Problem: ZHTTP is listed both as Draft & Stable

- 42/README.md
Solution: provide an abstract for the document that can be read in less than a minute.
I am having trouble creating a good summary because I am not sure I grasp the key points. I am also concerned in going in too many details. I have also some criticism on certain sections that I find a little too strict but that can be discussed elsewhere.
> WIP: Problem: C4 is hard to read for new contributors

- 27/README.md
Solution: specify that domain may not be empty
> Problem: unclear if domain may be empty (see zeromq/libzmq#2711)

- 37/README.md
Improve wording, and use correct value
> Wording regarding maximum value for heartbeat TTL is confusing

- 42/README.md
Solution: Fix the typo, "principle" => "principal"
> Problem: typo in the word "principal"

- 44/README.md
Solution: replace "principle" (noun) with "principal" (adjective) in "principal target platform".
> Problem: wrong word used in 44/C4

- 44/README.md
> Problem: key word is typed in lower case

- Makefile
- config.toml
- netlify.toml
Solution: Add Makefile and netlify.toml
> Problem: Build pipeline not setup

- .gitignore
- layouts/docs
- layouts/docs/single.html
Solution: Remove the symlink and overwrite the single file
> Problem: layout/docs does not overwrite theme because its a symlink

- content/menu/index.md
- layouts/docs/single.html
Solution: Guard the contributors expression
> Problem: Contributors are always listed even though there are none

- content/docs/rfcs/46/README.md
Solution: Change the license statement to refer to COSS and also compact license and language into preamble section
> Problem: The license statement does not refer to COSS

- content/docs/rfcs/36/README.md
- content/docs/rfcs/43/README.md
Solution: Update description for multi-part messages
Merge for issue #156
> Problem: ZRE description does not match the grammar

- content/docs/rfcs/44/README.md
Solution: Define these terms in the Preliminaries section
This is an attempt to close issue #116
> Problem: Founder and Administrator are not defined

- content/docs/rfcs/37/README.md
- content/docs/rfcs/41/README.md
- content/docs/rfcs/47/README.md
Solution: update the RFC to previous wording
> problem: wording of previous CLIENT-SERVER rfc is preferred

- content/docs/rfcs/46/README.md
Solution: Instead of address it must contain the topic name
> Problem: GET-HEADS description about topic content wrong

- content/docs/rfcs/42/README.md
> Change `master` branch to `main`
