spec_22.txt

Currently, C4 merely recommends that public contracts be documented.  However,
for my project's needs, I need this to be a hard requirement.  This PR alters
the text accordingly.

Tighten public contract documentation requirement.

---

spec_40.txt

Consider the following scenario.
You have an interactive client that is using XRAP to communicate with a server. Say an interactive music streamer, using the resource schema defined in the XRAP RFC.
Client is using a DEALER socket, server a ROUTER.
Server is NOT running.
Client makes a GET request for a resource.
Request times out, friendly message given to user.
Request message is in clients output queues.
Server starts up.
Request is then delivered to server, server responds.
Client then makes a GET request for a DIFFERENT resource.
Client receives response from the FIRST request. Wrong music plays. User unhappy.
I've tried this, and it works (does what I thought it would, i.e fail).
Consider also writing a multithreaded server. If clients are allowed to pipeline, then there's no …

Problem: Replies can get mismatched after timeouts, or slow servers

---

spec_41.txt

Specifically, it says ZMQ_SERVER does not block; it does in fact
block unless the client asks for DONT_WAIT.
Solution: fix the RFC.

Problem: ZMQ_SERVER specification is wrong

---

spec_42.txt

When an particular rule needs to be referred to, it needs to be quoted in full.
Solution: enumerate all "instrumental" sections.
This pull request is done as per a short exchange on Twitter: https://twitter.com/hintjens/status/732678600709812224

Problem: referring to rules of C4 is difficult

---

37/README.md
spec_37.txt

Specifically, it wrongly says server should send READY before
receiving & parsing READY from client.
Solution: clarify text; note the worked example is accurate.

Problem: description of NULL handshake is inaccurate

---

README.md

Solution: Update the link and change name from C4.1 to C4

Problem: README refers to older C4 as C4.1

---

7/README.md
SUMMARY.md

Note that 18/MDP is still 'draft'.
Solution: mark 7/MDP as 'stable'.

Problem: there is no stable MDP spec

---

book.js

Solution: new COSS plugin creates a shortcut for the shortname
For example /C4, or /ZMTP
This way, for example, http://rfc.zeromq.com/C4 will point to the last "actionable" version.

Problem: hard to find the latest version of a given spec

---

SUMMARY.md

Solution: XRAP spec is no longer Draft, thus remove it there.

Problem: Spec:40 is listed in Draft and Stable

---

42/README.md

Solution: use a working link for pull requests. Github's help seems to have changed - I am not sure what the original link was supposed to be, but this is the best i could find.
Closes: #112

Problem: incorrect link to pull requests

---

26/README.md

Fix some naming issues in the ABNF for the HELLO and INITIATE wire protocol.

26/CURVEZMQ Fix naming of messages in ABNF

---

43/README.md
SUMMARY.md

solution: propose ZYRE v3 RFC (rfc/43) with the ability to advertise CURVE keys in beacon packets.
when this gets merged- we may not want to "squash" the two commits, i purposely copied 36/README.md into 43/README.md as a base so  commenters could more easily see the differences between 36 and 43.
see: https://github.com/wesyoung/rfc/commit/8fbebfa8e326701458b3282246ef92a20dba38af

Problem: 36/ZYRE missing curve key in beacon packets

---

43/README.md

Solution: mention that beacons can also be announced and received over
IPv6, as czmq and zyre already support.
@wesyoung should the language be more specific? EG: mandate IPv4, suggest IPv6?

Problem: ZRE IPv6 beacon support not included in RFC

---

27/README.md

Solution: remove misleading words

Problem: example description claims "domain empty in this case", but it is not empty

---

37/README.md

Solution: limit it to 16 bytes which is plenty for debug data.
Unlike actual ping, whose context is part of the ICMP protocol and as
such handled by the operating system networking stack, allowing
arbitrarily long contexts in the ZMTP ping will cause memory to be
allocated in the application.

Problem: ZMTP 3.1 arbitrarily large context is open to abuse

---

content/docs/rfcs/45/README.md

Solution: Add a preamble containing the license statement and language description

Problem: Missing license statement

---

content/docs/rfcs/50/README.md
content/menu/index.md

Solution: Formalize the protcol used by czmq for many years for
encoding multiple messages as a single message. This is useful
for the new ZeroMQ socket types that only support sending
single messages.

Problem: Missing multipart message encoding

---

content/docs/rfcs/41/README.md
content/menu/index.md

Solution: Merge content of both RFC in a single one
This is an attempt to solve issue #152.
I kept the least recent one, that is RFC 41, but updated it with content from the RFC 47 that made sense to me.
There was some wording and I noted 2 main differences.
1. RFC 47 forbid multi-part messages
This seemed relevant for the Thread-Safe part of the pattern.
I do not master the ZeroMQ mysteries and maybe this is already dealt with how sockets receives messages, which seems to be an all or nothing from the user point of view.
Since it defines new sockets, I was not sure and kept it.
2. RFC 41 Block on sending from SERVER side
Since the SERVER will communicate with multiple CLIENTs, it seemed better to discard messages on full queue and not blocking sending in this case.

Problem: Multiple definition of Client-Server pattern

---

content/docs/rfcs/37/README.md

Solution: Fix specification name in the metadata
Solves https://github.com/zeromq/rfc/issues/176

Problem: RFC 37/ZMTP metadata name typo

---

content/docs/rfcs/37/README.md

Solution: Replace sparse table/grid with dense bullet list
Logic dictates that the number of socket types is likely to increase over time, so any layout where the width grows proportionate to their number is unsustainable.
The HTML `<br>` tags are... an unfortunate compromise, to keep the layout compact. But I'm open to alternatives!

Problem: RFC 37/ZMTP Table overflows page

---

content/docs/rfcs/43/README.md

This PR clarifies that it is not a requirement for a node to first join a group before it can shout messages in it.
Closes #189.

Clarify behaviour for shouting without joining
